services:
  redis:
    profiles: ["infra"]
    container_name: geoflip-redis
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  db:
    profiles: ["infra"]
    container_name: geoflip-db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    profiles: ["app"]
    container_name: geoflip-api
    build:
      context: ../server
    ports:
      - "8000:8000"
    environment:
      - ENV_STATE=${ENV_STATE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_SSL=${DB_SSL}
      - DATA_PATH=/home/data
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=http://localhost:8000
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=geoflip-redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SSL=${REDIS_SSL}
      - JOB_EXPIRY_TIME=${JOB_EXPIRY_TIME}
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ../server:/app
  client:
    profiles: ["app"]
    container_name: geoflip-client
    build:
      context: ../client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_MAPBOX_TOKEN: ${VITE_MAPBOX_TOKEN}
    ports:
      - "8080:80"
    depends_on:
      api:
        condition: service_started

volumes:
  postgres_data:
